### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by hwangJi-dev** [29th-WE-SOPT-iOS-Part/HwangJiEun#19]
## 📌  Feature Issue
Networking 과제
로그인 회원가입에 실제 API를 붙여보기

## 📝  To-do
- [x] 홈탭을 시작화면으로 설정
- [x] 프로필 버튼 클릭 시 로그인 화면이 뜨도록 설정
- [x] 로그인 서버 연결
- [x] 회원가입 서버 연결
- [x] 서버에서 넘겨주는 message Alert 띄우기 (로그인, 회원가입)
- [x] UserDefaults 활용하여 name 띄우기
