### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by hwangJi-dev** [29th-WE-SOPT-iOS-Part/HwangJiEun#26]
## 📌  Feature Issue
- TapGestureRecognizer를 이용하여 tap action 사용하기

## 📝  To-do
- [ ] ImageView에 tap gesture recognizer 달기
- [ ] imageView tap시 action (화면전환)
- [ ] 닫기 버튼 클릭시 dismiss
